### ISSUE TITLE
info

### ISSUE THREAD

**Issue by xtekky** [berryes/TikTunnel#2]
X-Bogus & _signature: request signature (security, generated for each request, hash + encryption of request args)
msToken: tracing cookie

https://github.com/pablouser1/SignTok (includes methods to generate both bogus & signature)

**Comment by berryes** [comment]
Thank you for the info! I'm having a hard time figuring out how the api really works but this covers the signatures part!
Maybe if i'll have the time i'll try to implement the generation method into rust but in the meanwhile i'll use this.
